import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../utils/supabaseClient';
import logo from '../../assets/CacheFlow_Logo.png';
import './OtpLogin.css';

function generateOTP() {
  // kept for compatibility; real OTP is generated by backend
  return null;
}

const OtpLogin = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState('login'); // 'login' | 'otp'
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [otp, setOtp] = useState(['', '', '', '', '', '']);
  const [sentOtp, setSentOtp] = useState('');
  const [timer, setTimer] = useState(45);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [contactNumber, setContactNumber] = useState('');
  const [userId, setUserId] = useState('');
  const [info, setInfo] = useState('');
  const [debugInfo, setDebugInfo] = useState('');
  const inputRefs = useRef([]);

  useEffect(() => {
    if (step === 'otp' && timer > 0) {
      const interval = setInterval(() => setTimer(t => t - 1), 1000);
      return () => clearInterval(interval);
    }
  }, [timer, step]);

  const handleChange = (idx, value) => {
    if (!/^[0-9]?$/.test(value)) return;
    const newOtp = [...otp];
    newOtp[idx] = value;
    setOtp(newOtp);
    if (value && idx < 5) {
      inputRefs.current[idx + 1].focus();
    }
  };

  const handleKeyDown = (idx, e) => {
    if (e.key === 'Backspace' && !otp[idx] && idx > 0) {
      inputRefs.current[idx - 1].focus();
    }
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    setError('');
    setInfo('');
    setDebugInfo('Login form submitted...');
    setLoading(true);

    // Short-circuit admin login: redirect directly to /admin without OTP
    if (username === 'admin' && password === 'admin123') {
      localStorage.setItem('admin_authenticated', 'true');
      setLoading(false);
      navigate('/admin');
      return;
    }

    // Check username/password in Supabase
    const { data, error: loginError } = await supabase
      .from('users')
      .select('id, contact_number')
      .eq('username', username)
      .eq('password', password)
      .single();

    setDebugInfo(`Database query: ${data ? 'User found' : 'No user found'}`);

    if (loginError || !data) {
      setError('Invalid username or password');
      setDebugInfo('Login failed - invalid credentials');
      setLoading(false);
      return;
    }

    if (!data.contact_number || data.contact_number.trim() === '') {
      setError('No contact number is associated with this account.');
      setDebugInfo('Login failed - no contact number found for user.');
      setLoading(false);
      return;
    }

    const trimmedContactNumber = data.contact_number.trim();
    setContactNumber(trimmedContactNumber);
    setUserId(data.id);
    setDebugInfo(`Contact number: ${trimmedContactNumber}`);

    // OTP DISABLED: Directly navigate to dashboard after credential check.
    localStorage.setItem('user_id', data.id);
    navigate('/dashboard');
    setLoading(false);
    return;

    /*
    // Request backend to generate and send the OTP
    try {
      const response = await fetch('http://localhost:3001/api/send-otp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ phoneNumbers: [trimmedContactNumber] })
      });

      const result = await response.json();

      if (response.ok && result.otp) {
        setSentOtp(result.otp);
        setTimer(45);
        setStep('otp');
        setInfo('OTP sent to your phone.');
        setDebugInfo('SMS sent successfully. OTP received for verification.');
      } else {
        setError('Failed to send OTP.');
        setDebugInfo(result.error || 'An unknown error occurred while sending OTP.');
        setInfo('');
      }
    } catch (err) {
      setError('Failed to connect to the server.');
      setDebugInfo(`Connection error: ${err.message}`);
      setInfo('');
      console.error('Server connection error:', err);
    }
    setLoading(false);
    */
  };

  const handleSendOtp = async () => {
    setError('');
    setInfo('');
    setLoading(true);

    try {
      const response = await fetch('http://localhost:3001/api/send-otp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ phoneNumbers: [contactNumber] })
      });

      const result = await response.json();

      if (response.ok && result.otp) {
        setSentOtp(result.otp);
        setTimer(45);
        setInfo('OTP resent to your phone.');
      } else {
        setError('Failed to resend OTP.');
        setInfo('');
      }
    } catch (err) {
      setError('Failed to connect to the server.');
      setInfo('');
      console.error('Server connection error:', err);
    }
    setLoading(false);
  };

  const handleVerify = (e) => {
    e.preventDefault();
    setError('');
    const entered = otp.join('').trim();
    const expected = (sentOtp || '').toString().trim();
    setDebugInfo(`Entered: ${entered} · Expected: ${expected ? '••••••' : '(none)'}`);
    if (entered === expected && expected !== '') {
      setSuccess(true);
      localStorage.setItem('user_id', userId);
      setTimeout(() => navigate('/dashboard'), 1000);
    } else {
      setError('Invalid code');
    }
  };

  return (
    <div className="otp-root">
      <div className="otp-layout">
        <div className="otp-left">
          <img src={logo} alt="CacheFlow Logo" className="otp-logo" />
          <div className="otp-desc">Experience simple, secure, and stress-free banking. Say goodbye to long queues and complex procedures and hello to hassle-free banking with Reen Bank.</div>
        </div>
        <div className="otp-right">
          {step === 'login' && (
            <form onSubmit={handleLogin} className="otp-form">
              <div className="otp-title">Login</div>
              <div className="otp-sub">Enter your username and password to continue</div>
              <input value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" className="otp-input" />
              <input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" className="otp-input" />
              <button type="submit" disabled={loading} className="otp-button">{loading ? 'Sending OTP...' : 'Send OTP'}</button>
              {error && <div className="otp-error">{error}</div>}
              {info && <div className="otp-info">{info}</div>}
              {debugInfo && <div className="otp-debug">{debugInfo}</div>}
            </form>
          )}

          {step === 'otp' && (
            <form onSubmit={handleVerify} className="otp-form">
              <div className="otp-title">Text Verification</div>
              <div className="otp-sub">A 6-digit code has been sent to your message <span className="otp-change">Change</span></div>
              <div className="otp-inputs">
                {otp.map((digit, idx) => (
                  <input
                    key={idx}
                    ref={el => inputRefs.current[idx] = el}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={digit}
                    onChange={e => handleChange(idx, e.target.value)}
                    onKeyDown={e => handleKeyDown(idx, e)}
                    className="otp-digit"
                  />
                ))}
              </div>
              <div className="otp-timer">0:{timer.toString().padStart(2, '0')} remaining</div>
              <button type="submit" disabled={loading || success} className="otp-button">Verify Text</button>
              <div className="otp-resend">Didn’t receive the code? <span className={`otp-resend-link ${timer === 0 ? 'enabled' : 'disabled'}`} onClick={() => timer === 0 && handleSendOtp()}>Resend</span></div>
              {error && <div className="otp-error">{error}</div>}
              {success && <div className="otp-success">Verified! Login successful.</div>}
            </form>
          )}
        </div>
      </div>
    </div>
  );
};

export default OtpLogin;
